### ISSUE TITLE
First Day of Week

### ISSUE THREAD

**Issue by erhansaydam** [arietimmerman/vue-responsive-calendar#1]
Hi,

This is very great calendar. However as ours, most countries use Monday as the first day of week. Can you add the feature to set the first day of week?

Best regards.

**Comment by arietimmerman** [comment]
Done. 
See the updated [demo](https://arietimmerman.github.io/vue-responsive-calendar/examples/). 

You can use it like this:

~~~.html
<responsive-calendar force-monday-first="true" max-size="l" :events="events"></responsive-calendar>
~~~

If you like it, please click the star button of this repo.

**Comment by erhansaydam** [comment]
Thank you very much.
